#!/usr/bin/php
<?php
/**
 * Gzip Minimized 1.0 - Copyright (c) 2015-2016 Infotoo International Limited - http://www.infotoo.com (MIT License)
 *
 * Last updated: 2016-05-04
 */

/*
 * The MIT license
 *
 * Copyright (C) 2015 Infotoo International Limited
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#path to 7-zip binary'
define('BIN_PATH', '/usr/bin/7z');

#================================= implementation =================================

if( count($argv)!=2 )
{
	echo 'Usage:  gzip-minimized  FILENAME'."\n";
	exit;
}

$match = null;
if( !preg_match('/\.min\.(css|js)$/',$argv[1],$match) )
{
	echo '"'.$argv[1].'" file extension is not ".min.css" or ".min.js"'."\n";
	exit;
}

if( !file_exists($argv[1]) )
{
	echo '"'.$argv[1].'" not exists'."\n";
	exit;
}

$source = $argv[1];
$gzipped = $source.'.gz';

if( file_exists($gzipped) )
{
	#remove exist gzip files first
	unlink($gzipped);
}
exec( BIN_PATH.' a -tgzip '.escapeshellarg($gzipped).' '.escapeshellarg($source) );
